- name: Install nginx
  apt:
    pkg: nginx
    update_cache: true
    cache_valid_time: 86400
    state: latest

- name: Disable default site
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  notify:
  - restart nginx
