- name: Install packages
  apt:
    pkg: '{{ item }}'
  with_items:
  - git

- name : Create user
  user:
    name: '{{ game_servers_bot_user }}'
    system: true

- name: Create directory
  file:
    dest: '{{ game_servers_bot_install_dir }}'
    state: directory
    group: '{{ game_servers_bot_user }}'
    owner: '{{ game_servers_bot_user }}'

- name: Clone repository
  become: true
  become_user: '{{ game_servers_bot_user }}'
  git:
    repo: https://github.com/RossHammer/game-servers.git
    dest: '{{ game_servers_bot_install_dir }}/repo'
  notify:
  - restart game-servers-bot

- name: Install packages
  become: true
  become_user: '{{ game_servers_bot_user }}'
  npm:
    path: '{{ game_servers_bot_install_dir }}/repo/discord-bot'
    production: true
  notify:
  - restart game-servers-bot

- set_fact:
    access_key_id: "{{ hostvars['localhost']['aws']['outputs']['bot_access_key_id']['value'] }}"
    secret_access_key: "{{ hostvars['localhost']['aws']['outputs']['bot_secret_access_key']['value'] }}"

- name: Create secrets
  template:
    src: env.j2
    dest: '{{ game_servers_bot_install_dir }}/env'
    group: '{{ game_servers_bot_user }}'
    owner: '{{ game_servers_bot_user }}'
    mode: '400'
  notify:
  - restart game-servers-bot

- name: Install service
  template:
    src: service.j2
    dest: /etc/systemd/system/game-servers-bot@{{ game_servers_bot_user }}.service
  notify:
  - restart game-servers-bot
