- hosts: localhost
  any_errors_fatal: true
  roles:
  - aws-resources
- hosts: home-assistant
  module_defaults:
    apt:
      update_cache: true
      cache_valid_time: 86400
      state: latest
  roles:
  - ssh
  - mqtt
  - home-assistant
