- name: Install packages
  apt:
    pkg: "{{ item }}"
  with_items:
  - python3
  - python3-venv
  - python3-pip

- name: Install awscli
  pip:
    name: awscli
    virtualenv: /opt/awscli
    virtualenv_command: /usr/bin/python3 -m venv
    state: latest

- name: Create link
  file:
    src: /opt/awscli/bin/aws
    dest: /usr/local/bin/aws
    state: link
