- name: Install packages
  apt:
    pkg:
      - python3
      - python3-venv
      - python3-pip

- name : Create user
  user:
    name: "{{ homeassistant_user }}"
    create_home: true
    append: true
    groups: dialout,gpio
    system: true

- name: Create directory
  file:
    dest: "{{ homeassistant_install_dir }}"
    state: directory
    group: "{{ homeassistant_group }}"
    owner: "{{ homeassistant_user }}"

- name: Install home-assistant
  become: true
  become_user: "{{ homeassistant_user }}"
  pip:
    name: homeassistant
    version: "{{ homeassistant_version }}"
    virtualenv: "{{ homeassistant_install_dir }}"
    virtualenv_command: /usr/bin/python3 -m venv
  notify:
  - restart home-assistant

- name: Install service
  template:
    src: service.j2
    dest: /etc/systemd/system/home-assistant@{{ homeassistant_user }}.service
  notify:
  - restart home-assistant

- name: Update nginx
  copy:
    src: files/nginx.config
    dest: /etc/nginx/sites-enabled/rosshammer.com
  notify:
  - restart nginx

- import_tasks: config.yml
