- name: Create node directory
  file:
    path: /opt/nodejs
    state: directory

- name: Download node
  get_url:
    url: https://nodejs.org/dist/v{{ node_version}}/node-v{{ node_version }}-linux-{{ ansible_architecture }}.tar.xz
    dest: /opt/nodejs/node-v{{ node_version }}-linux-{{ ansible_architecture }}.tar.xz

- name: Extract node
  unarchive:
    src: /opt/nodejs/node-v{{ node_version }}-linux-{{ ansible_architecture }}.tar.xz
    dest: /opt/nodejs
    remote_src: true
    creates: /opt/nodejs/node-v{{ node_version }}-linux-{{ ansible_architecture }}

- name: Link install
  file:
    src: /opt/nodejs/node-v{{ node_version }}-linux-{{ ansible_architecture }}/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  with_items:
  - node
  - npm
  - npx
