homeassistant:
  name: Home
  latitude: !secret home_location_latitude
  longitude: !secret home_location_longitude
  elevation: 688
  unit_system: metric
  time_zone: America/Edmonton
  customize: !include customize.yaml
  customize_glob:
    'group.all_*':
      hidden: false
      control: hidden

http:
  trusted_networks:
  - 127.0.0.1
  - 192.168.1.0/24
  base_url: rosshammer.com
  use_x_forwarded_for: true
  trusted_proxies:
  - 127.0.0.1

frontend:
config:
mqtt:
 broker: 127.0.0.1
# logger:
#   default: debug
updater:
discovery:
conversation:
recorder:
  purge_keep_days: 60
history:
logbook:
sun:
map:
owntracks:
  webhook_id: !secret owntracks_webhook_id
device_tracker:
notify:
- platform: pushbullet
  api_key: !secret pushbullet_api
tts:
- platform: google
neato:
  username: glitch17@gmail.com
  password: !secret neato_password
google_assistant:
  project_id: home-assistant-68df3
  api_key: AIzaSyCKZokgAcLanx0cVbrSbSAKP0dAdl6NzPg
  expose_by_default: false
  entity_config:
    switch.desk_light:
      expose: true
    switch.dining_room_light:
      expose: true
    switch.entrance_light:
      expose: true
    switch.kitchen_light:
      expose: true
    switch.living_room_light_east:
      expose: true
    switch.living_room_light_west:
      expose: true
zone:
- name: Work
  latitude: !secret work_location_latitude
  longitude: !secret work_location_longitude
  icon: mdi:domain

sensor:
- platform: yr
  monitored_conditions:
  - temperature
  - symbol
  - precipitation
  - windSpeed
  - pressure
  - humidity
  - cloudiness
- platform: cert_expiry
  host: rosshammer.com

- platform: command_line
  command: curl https://pypi.org/pypi/homeassistant/json | jq -r '.info.version'
  name: Latest Version
  scan_interval: 3600
- platform: version
  name: Installed version
- platform: uptime

switch:
- platform: tplink
  name: Dining room light
  host: 192.168.1.39
- platform: tplink
  name: Kitchen light
  host: 192.168.1.84
- platform: tplink
  name: Entrance light
  host: 192.168.1.203
- platform: mqtt
  name: Desk light
  state_topic: stat/desk_light/POWER
  command_topic: cmnd/desk_light/POWER
  availability_topic: tele/desk_light/LWT
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: Online
  payload_not_available: Offline
  retain: false
- platform: mqtt
  name: Living room light east
  state_topic: stat/living_room_light_east/POWER
  command_topic: cmnd/living_room_light_east/POWER
  availability_topic: tele/living_room_light_east/LWT
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: Online
  payload_not_available: Offline
  retain: false
- platform: mqtt
  name: Living room light west
  state_topic: stat/living_room_light_west/POWER
  command_topic: cmnd/living_room_light_west/POWER
  availability_topic: tele/living_room_light_west/LWT
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: Online
  payload_not_available: Offline
  retain: false

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
