homeassistant:
  name: Home
  latitude: !secret home_location_latitude
  longitude: !secret home_location_longitude
  elevation: 688
  unit_system: metric
  time_zone: America/Edmonton
  customize: !include customize.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 192.168.1.0/24
      allow_bypass_login: true
    - type: homeassistant

default_config:

http:
  base_url: rosshammer.com
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

tplink:
mqtt:
  broker: 127.0.0.1
# logger:
#   default: debug
recorder:
  purge_keep_days: 60
owntracks:
  webhook_id: !secret owntracks_webhook_id
tts:
  - platform: google_translate
neato:
  username: glitch17@gmail.com
  password: !secret neato_password
google_assistant:
  project_id: home-assistant-68df3
  service_account: !include service-account.json
  report_state: true
  expose_by_default: false
  entity_config:
    switch.desk_light:
      expose: true
      room: Main
    switch.dining_room_light:
      expose: true
      room: Main
    switch.kitchen_light:
      expose: true
      room: Main
    switch.living_room_lights:
      expose: true
      room: Main
    switch.entrance_light:
      expose: true
      room: Entryway
    switch.bedroom_light:
      expose: true
      room: Bedroom
    switch.christmas_tree:
      expose: true
zone:
  - name: Work
    latitude: !secret work_location_latitude
    longitude: !secret work_location_longitude
    radius: 200
    icon: mdi:domain

sensor:
  - platform: yr
  - platform: cert_expiry
    host: rosshammer.com
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
  - platform: command_line
    command: curl https://pypi.org/pypi/homeassistant/json | jq -r '.info.version'
    name: Latest Version
    scan_interval: 3600
  - platform: version
    name: Installed version
  - platform: uptime

switch:
  - platform: mqtt
    name: Desk light
    state_topic: stat/desk_light/POWER
    command_topic: cmnd/desk_light/POWER
    availability_topic: tele/desk_light/LWT
    qos: 1
    payload_on: 'ON'
    payload_off: 'OFF'
    payload_available: Online
    payload_not_available: Offline
    retain: false
  - platform: mqtt
    name: Living room lights
    state_topic: stat/living_room_lights/POWER
    command_topic: cmnd/living_room_lights/POWER
    availability_topic: tele/living_room_lights/LWT
    qos: 1
    payload_on: 'ON'
    payload_off: 'OFF'
    payload_available: Online
    payload_not_available: Offline
    retain: false
  # - platform: mqtt
  #   name: Christmas tree
  #   state_topic: stat/christmas_tree/POWER
  #   command_topic: cmnd/christmas_tree/POWER
  #   availability_topic: tele/christmas_tree/LWT
  #   qos: 1
  #   payload_on: 'ON'
  #   payload_off: 'OFF'
  #   payload_available: Online
  #   payload_not_available: Offline
  #   retain: false

automation: !include automations.yaml
script: !include scripts.yaml
