- name: Install packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 86400
  with_items:
  - jq

- name: Create config directory
  file:
    path: /home/homeassistant/.homeassistant
    state: directory
    group: homeassistant
    owner: homeassistant

- name: Copy plaintext configs
  copy:
    src: "{{ item }}"
    dest: "/home/homeassistant/.homeassistant/"
    group: homeassistant
    owner: homeassistant
  with_fileglob:
  - 'files/*.yaml'
  notify:
  - restart home-assistant

- name: Copy secrets
  template:
    src: templates/secrets.yaml.j2
    dest: /home/homeassistant/.homeassistant/secrets.yaml
    group: homeassistant
    owner: homeassistant
  notify:
  - restart home-assistant

- name: Check config
  become: true
  become_user: homeassistant
  command: /srv/homeassistant/bin/hass --script check_config -c "/home/homeassistant/.homeassistant"
  changed_when: false
