- name: Install packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
  - jq

- name: Copy plaintext configs
  copy:
    src: "files/{{ item }}"
    dest: "/home/homeassistant/.homeassistant/{{ item }}"
  with_items:
  - automations.yaml
  - configuration.yaml
  - customize.yaml
  - groups.yaml
  - known_devices.yaml
  - scripts.yaml
  notify:
  - restart home-assistant

- name: Copy secrets
  template:
    src: templates/secrets.yaml.j2
    dest: /home/homeassistant/.homeassistant/secrets.yaml
  notify:
  - restart home-assistant

- name: Check config
  become: true
  become_user: homeassistant
  command: /srv/homeassistant/bin/hass --script check_config -c "/home/homeassistant/.homeassistant"
  changed_when: false
