- name: Update git
  apt:
    pkg: git

- name: Create certificates
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_admin_email: glitch17@gmail.com
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services:
    - nginx
    certbot_certs:
    - domains:
      - rosshammer.com
    certbot_install_from_source: true
    certbot_auto_renew: False

- name: Add cron job for certbot renewal
  cron:
      name: Certbot automatic renewal.
      job: "systemctl stop nginx && {{ certbot_script }} renew --quiet --no-self-upgrade; systemctl start nginx"
      minute: 20
      hour: 3
