- id: 452D43CE-FE81-4609-87A9-E6DE387A9461
  alias: Update Check
  trigger:
  - platform: event
    event_type: 'state_changed'
    event_data:
      entity_id: sensor.latest_version
  condition:
  - condition: template
    value_template: '{{ states.sensor.latest_version.state != states.sensor.installed_version.state }}'
  action:
  - service: notify.notify
    data:
      message: 'Update available v{{ states.sensor.latest_version.state }} (Currently v{{ states.sensor.installed_version.state }})'
