homeassistant:
  name: Home
  latitude: !secret home_location_latitude
  longitude: !secret home_location_longitude
  elevation: 688
  unit_system: metric
  time_zone: America/Edmonton
  customize: !include customize.yaml

http:
  api_password: !secret password
  trusted_networks:
  - 127.0.0.1
  - 192.168.1.0/24
  base_url: rosshammer.com
  use_x_forwarded_for: true
  trusted_proxies:
  - 127.0.0.1

frontend:
config:
mqtt:
 broker: 127.0.0.1
# logger:
#   default: debug
updater:
discovery:
conversation:
history:
logbook:
sun:
map:
device_tracker:
- platform: owntracks_http
notify:
- platform: pushbullet
  api_key: !secret pushbullet_api
tts:
- platform: google
neato:
  username: glitch17@gmail.com
  password: !secret neato_password

zone:
- name: Work
  latitude: !secret work_location_latitude
  longitude: !secret work_location_longitude
  icon: mdi:domain

sensor:
- platform: yr
  monitored_conditions:
  - temperature
  - symbol
  - precipitation
  - windSpeed
  - pressure
  - humidity
  - cloudiness
- platform: cert_expiry
  host: rosshammer.com

- platform: command_line
  command: curl https://pypi.org/pypi/homeassistant/json | jq -r '.info.version'
  name: Latest Version
  scan_interval: 3600
- platform: command_line
  command: cat /home/homeassistant/.homeassistant/.HA_VERSION
  name: Installed version
- platform: uptime

switch:
- platform: tplink
  name: Dining room light
  host: 192.168.1.39
- platform: tplink
  name: Kitchen light
  host: 192.168.1.84
- platform: tplink
  name: Entrance light
  host: 192.168.1.203

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
